//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrmposZamanlıKurGüncelleme
{
    using System;
    using System.Collections.Generic;
    
    public partial class TCMB_KUR_CRMPOS
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> TARIH { get; set; }
        public Nullable<decimal> ALIS { get; set; }
        public Nullable<decimal> SATIS { get; set; }
        public Nullable<long> DOVIZ_AD { get; set; }
        public Nullable<int> SIRA { get; set; }
    }
}
